M48
; DRILL file {KiCad 9.0.1} date 2026-05-05T10:13:53+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-05T10:13:53+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X124.75Y-61.5
X124.75Y-67.0
T2
X83.8Y-137.32
X94.5Y-137.32
X109.3Y-137.25
X120.0Y-137.25
M30
